### ISSUE TITLE
Can’t make «class fvtg» of window 1 of application "Finder" into type alias

### ISSUE THREAD

**Issue by ksm** [rkanter/Open-iTerm-or-Terminal-Here...#2]
Hey, I ran `./generate.sh iterm`. Put the generated script into my finder toolbar. But whenever I tap on it I get this error:

<img width="532" alt="Screen Shot 2019-04-29 at 11 16 43 AM" src="https://user-images.githubusercontent.com/747910/56906505-59fac980-6a70-11e9-80de-53af09c78c67.png">

Running macOS Mojave 10.14.4.

**Comment by rkanter** [comment]
Hi,

According to https://apple.stackexchange.com/a/37772, it looks like this happens if the Finder window contains a search result or other "special" thing.  I tried that and I get this error too.  Is your frontmost Finder window search result, smart folder, etc?

I don't think there's a workaround for this because those places don't really exist in the filesystem (so Terminal can't go there), but I'll look into updating the app sometime this week to make it give a nicer message when this happens.

**Comment by rkanter** [comment]
a465f0d038057153b024ae127ae814ed34cd25a2 improves this by giving a clearer message about why it can't go there.  While I was at it, I also added a check and nicer message when there are no Finder windows.

Please pull the latest and regenerate.

**Comment by ksm** [comment]
@rkanter Thanks for the update and thank for your work on this project! Nice to see a better error message. 

I'm pretty sure I was trying to open a regular directory containing some projects I'm coding on.

When I find some time I'll try to dig in to see if I can get this to work for me.
